[package]
name = "rusty_mtw_server"
version = "0.1.0"
edition = "2021"
authors = ["eta carinae"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
